
server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
spring:   
  cloud:
    gateway:
      routes:
      - id: watermarkService
        uri:  lb://WATERMARK-SERVICE
        predicates:
        - Path=/**
