
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
      
spring:   
  cloud:
    gateway:
      routes:
      - id: watermarkService
        uri:  lb://WATERMARK-API-SERVICE
        predicates:
        - Path=/** 
