

eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/imagedb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true 
    hibernate: 
      ddl-auto: update
      
path:
  values: C:\\Users\\MohammedRinishA\\Pictures\\Downloads
  


  
  
