
server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/imagedb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true 
    hibernate: 
      ddl-auto: update
      
path:
  values: C:\\Users\\MohammedRinishA\\Pictures\\Downloads\\
  
destination:
  values: C:\\Users\\MohammedRinishA\\Pictures\\ImageMagick\\Downloads\\

  

