
server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/imagedb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true 
    hibernate: 
      ddl-auto: update
      
path:
  values: C:\\Users\\MohammedRinishA\\Pictures\\Downloads\\
  
  
command:
  values: "cmd /c magick convert Bird.jpg  -font georgia -gravity Center -pointsize 400 -fill white -evaluate multiply 0.35 -annotate -30x-30 ----ACCEPTED---- code2.jpeg"


  

