
server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/imagedb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true 
    hibernate: 
      ddl-auto: update
      
path:
  values: C:\\Users\\MohammedRinishA\\Pictures\\Downloads\\
  
command:
  values1:  cmd /c magick convert
command:
  values2:  -font Arial -pointsize 35 -draw  gravity center fill white text 5,-35 
  
  
